source/RatingTracker.Web.Mvc/Models/Game/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RatingTracker.Models.Game
{
    public class CreateViewModel
    {
        public string LeagueName { get; set; }
        public int LeagueId { get; set; }
        public int SelectedWinnerId { get; set; }
        public int SelectedLoserId { get; set; }
        public SelectList PlayerSelectList { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/AddPlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;
using System.Web.Mvc;

namespace RatingTracker.Models.League
{
    public class AddPlayerViewModel
    {
        public SelectList Players { get; set; }
        public int SelectedPlayerId { get; set; }
        public int LeagueId { get; set; }
        public string LeagueName { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RatingTracker.Models.League
{
    public class CreateViewModel
    {
        [StringLength(150)]
        public string Name { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;

namespace RatingTracker.Models.League
{
    public class DetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<LeagueGameDetailEntity> Games { get; set; }
        public IEnumerable<LeaguePlayerDetailEntity> Players { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Controllers/GameController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using RatingTracker.Application;
using RatingTracker.DatabaseSpecific;
using RatingTracker.EntityClasses;
using RatingTracker.HelperClasses;
using RatingTracker.Models.Game;
using SD.LLBLGen.Pro.ORMSupportClasses;


namespace RatingTracker.Controllers
{
    public class GameController : Controller
    {
        public ActionResult Index()
        {
            var vm = new IndexViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                var allGames = new EntityCollection<LeagueGameDetailEntity>();
                adapter.FetchEntityCollection(allGames, null);
                vm.Games = allGames.OrderBy(m => m.TimeStamp);
            }

            return View(vm);
        }

        [Authorize]
        public ActionResult Create(int id)
        {
            var playerQuery = new PlayerQuery();
            var league = new LeagueEntity(id);

            using (var adapter = new DataAccessAdapter())
            {
                adapter.FetchEntity(league);
            }

            var players = playerQuery.GetPlayersForLeague(id);

            var vm = new CreateViewModel
            {
                PlayerSelectList = new SelectList(players.OrderBy(m => m.Name), "LeaguePlayerId", "Name"),
                LeagueName = league.Name,
                LeagueId = id
            };

            return View(vm);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel form)
        {
            var service = new GameService();

            try
            {
                service.Create(form.SelectedWinnerId, form.SelectedLoserId);
                return RedirectToAction("Details", "League", new { id = form.LeagueId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            var vm = new DeleteViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                var toDelete = new LeagueGameDetailEntity(id);
                adapter.FetchEntity(toDelete);
                vm.Game = toDelete;
            }

            return View(vm);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete(DeleteViewModel form)
        {
            var service = new GameService();

            try
            {
                service.Delete(form.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult Calculate()
        {
            return View();
        }


        [HttpPost]
        [Authorize]
        public ActionResult Calculate(CalculateViewModel form)
        {
            var service = new RatingCalculationService();

            try
            {
                service.RecalculateAllRatings();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
    }
}

source/RatingTracker.Web.Mvc/Controllers/LeagueController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using RatingTracker.Application;
using RatingTracker.DatabaseSpecific;
using RatingTracker.EntityClasses;
using RatingTracker.HelperClasses;
using RatingTracker.Models.League;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RatingTracker.Controllers
{
    public class LeagueController : Controller
    {
        public ActionResult Index()
        {
            var vm = new IndexViewModel();

            var query = new LeagueQuery();
            vm.Leagues = query.GetAll();

            return View(vm);
        }

        public ActionResult Details(int id)
        {
            var vm = new DetailsViewModel { Id = id };

            using (var adapter = new DataAccessAdapter())
            {
                var league = new LeagueEntity(id);
                adapter.FetchEntity(league);
                vm.Name = league.Name;

                var players = new EntityCollection<LeaguePlayerDetailEntity>();
                var playerFilter = new RelationPredicateBucket(LeaguePlayerDetailFields.LeagueId == id);
                adapter.FetchEntityCollection(players, playerFilter);
                vm.Players = players;

                var games = new EntityCollection<LeagueGameDetailEntity>();
                var gameFilter = new RelationPredicateBucket(LeagueGameDetailFields.LeagueId == id);
                adapter.FetchEntityCollection(games, gameFilter);
                vm.Games = games;
            }

            return View(vm);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult History(int id)
        {
            var vm = new HistoryViewModel { LeagueId = id };
            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel form)
        {
            try
            {
                var service = new LeagueService();
                service.Create(form.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult AddPlayer(int id)
        {
            var vm = new AddPlayerViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                // for now, getting all players - update this to exclude players already in league
                var eligiblePlayers = new EntityCollection<PlayerEntity>();
                adapter.FetchEntityCollection(eligiblePlayers, null);
                var league = new LeagueEntity(id);
                adapter.FetchEntity(league);
                vm.Players = new SelectList(eligiblePlayers.OrderBy(m => m.Name), "Id", "Name");
                vm.LeagueId = id;
                vm.LeagueName = league.Name;
            }

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPlayer(AddPlayerViewModel form)
        {
            try
            {
                var service = new LeagueService();

                service.AddPlayer(form.LeagueId, form.SelectedPlayerId);

                return RedirectToAction("Details", new { id = form.LeagueId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult RemovePlayer(int id)
        {
            var vm = new RemovePlayerViewModel { ToRemoveId = id };

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemovePlayer(RemovePlayerViewModel form)
        {
            try
            {
                var service = new LeagueService();
                service.RemovePlayer(form.ToRemoveId);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
    }
}

source/RatingTracker.Web.Mvc/Controllers/PlayerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using RatingTracker.DatabaseSpecific;
using RatingTracker.EntityClasses;
using RatingTracker.HelperClasses;
using RatingTracker.Models.Player;
using SD.LLBLGen.Pro.ORMSupportClasses;
using RatingTracker.Application;

namespace RatingTracker.Controllers
{
    public class PlayerController : Controller
    {
        public ActionResult Index()
        {
            var query = new PlayerQuery();
            var vm = new IndexViewModel();
            vm.Players = query.GetAll();

            return View(vm);
        }

        public ActionResult Profile(int id)
        {
            var vm = new ProfileViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                var playerGames = new EntityCollection<LeagueGameDetailEntity>();
                var filter = new RelationPredicateBucket(LeagueGameDetailFields.LoserPlayerId == id | LeagueGameDetailFields.WinnerPlayerId == id);

                adapter.FetchEntityCollection(playerGames, filter);
                vm.Games = playerGames;
                var player = new PlayerEntity(id);
                adapter.FetchEntity(player);
                vm.Player = player;

                var leagues = new EntityCollection<LeaguePlayerDetailEntity>();
                var leagueFilter = new RelationPredicateBucket(LeaguePlayerDetailFields.PlayerId == id);
                adapter.FetchEntityCollection(leagues, leagueFilter);
                vm.Leagues = leagues;
            }

            return View(vm);
        }

        public ActionResult League(int id)
        {
            var vm = new LeagueViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                var playerGames = new EntityCollection<LeagueGameDetailEntity>();
                var filter = new RelationPredicateBucket(LeagueGameDetailFields.LoserId == id | LeagueGameDetailFields.WinnerId == id);
                adapter.FetchEntityCollection(playerGames, filter);
                vm.Games = playerGames;

                var leaguePlayer = new LeaguePlayerEntity(id);
                adapter.FetchEntity(leaguePlayer);
                vm.LeaguePlayer = leaguePlayer;

                var player = new PlayerEntity(leaguePlayer.PlayerId);
                adapter.FetchEntity(player);
                vm.Player = player;

                var postGameRatings = new EntityCollection<PostGameRatingDetailEntity>();
                var ratingFilter = new RelationPredicateBucket(PostGameRatingDetailFields.LeaguePlayerId == id);
                adapter.FetchEntityCollection(postGameRatings, ratingFilter);
                vm.MaxRating = postGameRatings.Max(m => m.Rating);
            }

            return View(vm);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel form)
        {
            try
            {
                var service = new PlayerService();
                service.Create(form.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var query = new PlayerQuery();
            var player = query.Get(id);
            var vm = new EditViewModel
            {
                Name = player.Name,
                Id = id
            };

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditViewModel form)
        {
            try
            {
                var query = new PlayerQuery();
                var service = new PlayerService();

                var player = query.Get(form.Id);

                player.Name = form.Name;

                service.Save(player);
                return RedirectToAction("Profile", new { form.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public JsonResult RatingsOverTime(int id)
        {
            using (var adapter = new DataAccessAdapter())
            {
                var ratings = new EntityCollection<PostGameRatingDetailEntity>();
                var filter = new RelationPredicateBucket(PostGameRatingDetailFields.LeagueId == id);
                adapter.FetchEntityCollection(ratings, filter);

                var players = ratings.GroupBy(m => m.PlayerId);

                var result = new List<RatingResult>();

                foreach (var player in players)
                {
                    var toAdd = new RatingResult
                    {
                        PlayerName = player.First().PlayerName,
                        TimeRating = player
                            .OrderByDescending(m => m.TimeStamp)
                            .Take(100)
                            .OrderBy(m => m.TimeStamp)
                            .Select(m => new Tuple<string, short>(m.TimeStamp.ToString("M/d/y h:m:s"), m.Rating))
                            .ToArray()
                    };
                    result.Add(toAdd);
                }

                var toRet = result.Select(m => new
                {
                    name = m.PlayerName,
                    data = m.TimeRating.Select(n => new
                    {
                        x = n.Item1,
                        y = n.Item2
                    })
                });

                return Json(toRet.ToArray(), JsonRequestBehavior.AllowGet);
            }
        }

        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public JsonResult Record(int id)
        {
            var games = new EntityCollection<GameEntity>();
            var filter = new RelationPredicateBucket(GameFields.WinnerId == id | GameFields.LoserId == id);

            using (var adapter = new DataAccessAdapter())
            {
                adapter.FetchEntityCollection(games, filter);
            }

            var toRet = games.OrderBy(m => m.TimeStamp).Select(m => new
            {
                val = m.WinnerId == id ? 1 : -1
            });

            return Json(toRet.Take(100).Select(m => m.val).ToArray(), JsonRequestBehavior.AllowGet);
        }

        public static double DateTimeToUnixTimestamp(DateTime dateTime)
        {
            return (dateTime - new DateTime(1970, 1, 1).ToLocalTime()).TotalSeconds;
        }

        private class RatingResult
        {
            public string PlayerName { get; set; }
            public IEnumerable<Tuple<string, short>> TimeRating { get; set; }
        }

        //public ActionResult Edit(int id)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Edit(EditViewModel form)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}

        //public ActionResult Delete(int id)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Delete(DeleteViewModel form)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}
    }
}

source/RatingTracker.Web.Mvc/Views/League/AddPlayer.cshtml
@model RatingTracker.Models.League.AddPlayerViewModel
@{
    ViewBag.Title = "Add League Players";
}
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm("AddPlayer", "League", null, FormMethod.Post, new { role = "form" }))
        {
            <h1>Add Player to @Model.LeagueName</h1>
            <div class="panel panel-default">
                <div class="panel-body">
                    @Html.ValidationSummary()
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label>Player</label>
                        @Html.DropDownListFor(m => m.SelectedPlayerId, Model.Players, new { @class = "form-control" })
                    </div>
                    @Html.HiddenFor(m => m.LeagueId)


                    <input type="submit" class="btn btn-success" value="Submit" />
                    @Html.ActionLink("Create Players", "Create", "Player", null, new { @class = "btn btn-info" })


                </div>
            </div>
            
        }
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/League/Create.cshtml
@model RatingTracker.Models.League.CreateViewModel
@{
    ViewBag.Title = "Add New League";
}
<div class="row">
    <div class="col-xs-12">
        <h1>Add League</h1>

        @using (Html.BeginForm("Create", "League", null, FormMethod.Post, new { role = "form" }))
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    @Html.ValidationSummary()
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label>Name</label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                    <input type="submit" class="btn btn-success" value="Submit" />
                </div>
            </div>
        }
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/League/Details.cshtml
@model RatingTracker.Models.League.DetailsViewModel
@{
    ViewBag.Title = "League Details";
}



<div class="row">
    <div class="col-xs-12">
        <h1>
            @Model.Name
        </h1>
        <div class="hidden-xs hidden-sm">
            <a href="/league" class="btn btn-primary">Back</a>
            @Html.ActionLink("Record Game", "Create", "Game", new { Model.Id }, new { @class = "btn btn-info" })
            @Html.ActionLink("Add Player", "AddPlayer", new { Model.Id }, new { @class = "btn btn-success" })
            @Html.ActionLink("Ratings History", "History", new { Model.Id }, new { @class = "btn btn-default" })
        </div>
        <div class="hidden-lg hidden-md">
            <a href="/league" class="btn btn-primary btn-xs">Back</a>
            @Html.ActionLink("Record Game", "Create", "Game", new { Model.Id }, new { @class = "btn btn-info btn-xs" })
            @Html.ActionLink("Add Player", "AddPlayer", new { Model.Id }, new { @class = "btn btn-success btn-xs" })
            @Html.ActionLink("Ratings History", "History", new { Model.Id }, new { @class = "btn btn-default btn-xs" })
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>League Rankings</h2>
        <table class="table table-condensed">
            <tr><th>Rank</th><th>Player</th><th>Current Rating</th></tr>
            @for (int i = 0; i < Model.Players.Count(); i++)
            {
                var player = Model.Players.OrderByDescending(m=>m.CurrentRating).ElementAt(i);
                var prevPlayer = i == 0 ? null : Model.Players.OrderByDescending(m=>m.CurrentRating).ElementAt(i - 1);
                <tr>
                    @if (i > 0 && player.CurrentRating == prevPlayer.CurrentRating)
                    {
                        <td> - </td>
                    }
                    else
                    {
                        <td>@(i + 1).</td>
                    }
                    <td>@Html.ActionLink(player.Name, "League", "Player", new { id = player.LeaguePlayerId }, null)</td>
                    <td>@player.CurrentRating</td>
                </tr>
            }

        </table>
    </div>
    <div class="col-md-6">
        <h2>Game History</h2>
        <table class="table table-condensed">
            <tr><th>&nbsp;</th><th>Winner</th><th>Loser</th><th>Date</th></tr>
            @foreach (var game in Model.Games.OrderByDescending(m => m.TimeStamp).Take(25))
            {
                if (game.IsCriticalUpset)
                {
                    <tr class="danger">
                        <td>@Html.ActionLink("Delete", "Delete", "Game", new { id = game.GameId }, new { @class = "btn btn-xs btn-danger" })</td>
                        <td class="text-success">@game.WinnerName (@(Math.Round(game.Bias * 100, 1))%)</td>
                        <td class="text-danger">@game.LoserName (@(Math.Round(100 - game.Bias * 100, 1))%)</td>
                        <td>@game.TimeStamp</td>
                    </tr>
                }
                else if (game.IsUpset)
                {

                    <tr class="warning">
                        <td>@Html.ActionLink("Delete", "Delete", "Game", new { id = game.GameId }, new { @class = "btn btn-xs btn-danger" })</td>
                        <td class="text-success">@game.WinnerName (@(Math.Round(game.Bias * 100, 1))%)</td>
                        <td class="text-danger">@game.LoserName (@(Math.Round(100 - game.Bias * 100, 1))%)</td>
                        <td>@game.TimeStamp</td>
                    </tr>
                }
                else
                {
                    <tr>
                        <td>@Html.ActionLink("Delete", "Delete", "Game", new { id = game.GameId }, new { @class = "btn btn-xs btn-danger" })</td>
                        <td class="text-success">@game.WinnerName (@(Math.Round(game.Bias * 100, 1))%)</td>
                        <td class="text-danger">@game.LoserName (@(Math.Round(100 - game.Bias * 100, 1))%)</td>
                        <td>@game.TimeStamp</td>
                    </tr>
                }
            }
        </table>
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/League/History.cshtml
@{
    ViewBag.Title = "Rating History";
}

<h1>Rating History</h1>

<div class="row">
    <div class="col-xs-12">
        @Html.ActionLink("League Details", "Details", "League", new { id = Model.LeagueId }, new { @class = "btn btn-default" })

        <div id="chart"></div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/d3/d3.min.js"></script>
    <script src="~/Scripts/c3.min.js"></script>
    <script type="text/javascript">

        $(function () {
            $.get("/player/ratingsovertime/@Model.LeagueId", function (data) {
                var columns = GetColumns(data);

                var chart = c3.generate({
                    type: 'spline',
                    bindto: '#chart',
                    data: {
                        x: 'x',
                        columns: columns
                    }
                });
            });


        });

        var GetColumns = function(data) {

            var toRet = [];
            var players = [];
            var x = [];
            x.push('x');

            for (i = 0; i < data.length; i++) {
                var player = data[i];
                var ratings = [];
                ratings.push(player.name);
                x.push(0);
                for (j = 0; j < player.data.length; j++) {
                    var rating = player.data[j];
                    ratings.push(rating.y);
                    if (i === 0) {
                        x.push(j + 1);
                    }

                }
                players.push(ratings);
            }

            toRet.push(x);

            players.sort(function (a, b) {
                var x = a[0].toLowerCase(), y = b[0].toLowerCase();
                return x < y ? -1 : x > y ? 1 : 0;
            });

            for (var i = 0; i < players.length; i++) {
                toRet.push(players[i]);
            }

            return toRet;
        };

    </script>
}

source/RatingTracker.Web.Mvc/Views/League/Index.cshtml
@model RatingTracker.Models.League.IndexViewModel
@{
    ViewBag.Title = "Leagues";
}

<h1>Leagues</h1>

<div class="row">
    <div class="col-xs-12">

        <div class="list-group">
            @foreach (var league in Model.Leagues)
            {
                @Html.ActionLink(league.Name, "Details", "League", new { id = league.Id }, new { @class = "list-group-item" })
            }
        </div>


        @Html.ActionLink("Add League", "Create", null, new { @class = "btn btn-primary" })
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/League/RemovePlayer.cshtml
@model RatingTracker.Models.League.RemovePlayerViewModel
@{
    ViewBag.Title = "Remove League Player";
}
<div class="row">
    <div class="col-xs-12">
        <p>Are you sure you wish to remove this player from the league?</p>
        @using (Html.BeginForm("RemovePlayer", "League", null, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            
            @Html.HiddenFor(m=>m.ToRemoveId)
            <input type="submit" class="btn btn-success" value="Submit"/>
        }
    </div>
</div>