source/RatingTracker.Web.Mvc/Models/Game/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RatingTracker.Models.Game
{
    public class CreateViewModel
    {
        public string LeagueName { get; set; }
        public int LeagueId { get; set; }
        public int SelectedWinnerId { get; set; }
        public int SelectedLoserId { get; set; }
        public SelectList PlayerSelectList { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/AddPlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;
using System.Web.Mvc;

namespace RatingTracker.Models.League
{
    public class AddPlayerViewModel
    {
        public SelectList Players { get; set; }
        public int SelectedPlayerId { get; set; }
        public int LeagueId { get; set; }
        public string LeagueName { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RatingTracker.Models.League
{
    public class CreateViewModel
    {
        [StringLength(150)]
        public string Name { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;

namespace RatingTracker.Models.League
{
    public class DetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<LeagueGameDetailEntity> Games { get; set; }
        public IEnumerable<LeaguePlayerDetailEntity> Players { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/HistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RatingTracker.Models.League
{
    public class HistoryViewModel
    {
        public int LeagueId { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;

namespace RatingTracker.Models.League
{
    public class IndexViewModel
    {
        public IEnumerable<LeagueEntity> Leagues { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/League/RemovePlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;
using System.Web.Mvc;

namespace RatingTracker.Models.League
{
    public class RemovePlayerViewModel
    {
        public int ToRemoveId { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/Player/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RatingTracker.Models.Player
{
    public class CreateViewModel
    {
        [StringLength(150)]
        public string Name { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/Player/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RatingTracker.Models.Player
{
    public class EditViewModel
    {
        [StringLength(150)]
        public string Name { get; set; }
        public int Id { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/Player/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;

namespace RatingTracker.Models.Player
{
    public class IndexViewModel
    {
        public IEnumerable<PlayerEntity> Players { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/Player/LeagueViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;

namespace RatingTracker.Models.Player
{
    public class LeagueViewModel
    {
        public IEnumerable<LeagueGameDetailEntity> Games { get; set; }
        public PlayerEntity Player { get; set; }
        public LeaguePlayerEntity LeaguePlayer { get; set; }

        public int MaxRating { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Models/Player/ProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RatingTracker.EntityClasses;

namespace RatingTracker.Models.Player
{
    public class ProfileViewModel
    {
        public IEnumerable<LeagueGameDetailEntity> Games { get; set; }
        public PlayerEntity Player { get; set; }

        public IEnumerable<LeaguePlayerDetailEntity> Leagues { get; set; }
    }
}

source/RatingTracker.Web.Mvc/Controllers/LeagueController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using RatingTracker.Application;
using RatingTracker.DatabaseSpecific;
using RatingTracker.EntityClasses;
using RatingTracker.HelperClasses;
using RatingTracker.Models.League;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RatingTracker.Controllers
{
    public class LeagueController : Controller
    {
        public ActionResult Index()
        {
            var vm = new IndexViewModel();

            var query = new LeagueQuery();
            vm.Leagues = query.GetAll();

            return View(vm);
        }

        public ActionResult Details(int id)
        {
            var vm = new DetailsViewModel { Id = id };

            using (var adapter = new DataAccessAdapter())
            {
                var league = new LeagueEntity(id);
                adapter.FetchEntity(league);
                vm.Name = league.Name;

                var players = new EntityCollection<LeaguePlayerDetailEntity>();
                var playerFilter = new RelationPredicateBucket(LeaguePlayerDetailFields.LeagueId == id);
                adapter.FetchEntityCollection(players, playerFilter);
                vm.Players = players;

                var games = new EntityCollection<LeagueGameDetailEntity>();
                var gameFilter = new RelationPredicateBucket(LeagueGameDetailFields.LeagueId == id);
                adapter.FetchEntityCollection(games, gameFilter);
                vm.Games = games;
            }

            return View(vm);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult History(int id)
        {
            var vm = new HistoryViewModel { LeagueId = id };
            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel form)
        {
            try
            {
                var service = new LeagueService();
                service.Create(form.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult AddPlayer(int id)
        {
            var vm = new AddPlayerViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                // for now, getting all players - update this to exclude players already in league
                var eligiblePlayers = new EntityCollection<PlayerEntity>();
                adapter.FetchEntityCollection(eligiblePlayers, null);
                var league = new LeagueEntity(id);
                adapter.FetchEntity(league);
                vm.Players = new SelectList(eligiblePlayers.OrderBy(m => m.Name), "Id", "Name");
                vm.LeagueId = id;
                vm.LeagueName = league.Name;
            }

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPlayer(AddPlayerViewModel form)
        {
            try
            {
                var service = new LeagueService();

                service.AddPlayer(form.LeagueId, form.SelectedPlayerId);

                return RedirectToAction("Details", new { id = form.LeagueId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult RemovePlayer(int id)
        {
            var vm = new RemovePlayerViewModel { ToRemoveId = id };

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemovePlayer(RemovePlayerViewModel form)
        {
            try
            {
                var service = new LeagueService();
                service.RemovePlayer(form.ToRemoveId);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
    }
}

source/RatingTracker.Web.Mvc/Controllers/PlayerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using RatingTracker.DatabaseSpecific;
using RatingTracker.EntityClasses;
using RatingTracker.HelperClasses;
using RatingTracker.Models.Player;
using SD.LLBLGen.Pro.ORMSupportClasses;
using RatingTracker.Application;

namespace RatingTracker.Controllers
{
    public class PlayerController : Controller
    {
        public ActionResult Index()
        {
            var query = new PlayerQuery();
            var vm = new IndexViewModel();
            vm.Players = query.GetAll();

            return View(vm);
        }

        public ActionResult Profile(int id)
        {
            var vm = new ProfileViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                var playerGames = new EntityCollection<LeagueGameDetailEntity>();
                var filter = new RelationPredicateBucket(LeagueGameDetailFields.LoserPlayerId == id | LeagueGameDetailFields.WinnerPlayerId == id);

                adapter.FetchEntityCollection(playerGames, filter);
                vm.Games = playerGames;
                var player = new PlayerEntity(id);
                adapter.FetchEntity(player);
                vm.Player = player;

                var leagues = new EntityCollection<LeaguePlayerDetailEntity>();
                var leagueFilter = new RelationPredicateBucket(LeaguePlayerDetailFields.PlayerId == id);
                adapter.FetchEntityCollection(leagues, leagueFilter);
                vm.Leagues = leagues;
            }

            return View(vm);
        }

        public ActionResult League(int id)
        {
            var vm = new LeagueViewModel();

            using (var adapter = new DataAccessAdapter())
            {
                var playerGames = new EntityCollection<LeagueGameDetailEntity>();
                var filter = new RelationPredicateBucket(LeagueGameDetailFields.LoserId == id | LeagueGameDetailFields.WinnerId == id);
                adapter.FetchEntityCollection(playerGames, filter);
                vm.Games = playerGames;

                var leaguePlayer = new LeaguePlayerEntity(id);
                adapter.FetchEntity(leaguePlayer);
                vm.LeaguePlayer = leaguePlayer;

                var player = new PlayerEntity(leaguePlayer.PlayerId);
                adapter.FetchEntity(player);
                vm.Player = player;

                var postGameRatings = new EntityCollection<PostGameRatingDetailEntity>();
                var ratingFilter = new RelationPredicateBucket(PostGameRatingDetailFields.LeaguePlayerId == id);
                adapter.FetchEntityCollection(postGameRatings, ratingFilter);
                vm.MaxRating = postGameRatings.Max(m => m.Rating);
            }

            return View(vm);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel form)
        {
            try
            {
                var service = new PlayerService();
                service.Create(form.Name);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var query = new PlayerQuery();
            var player = query.Get(id);
            var vm = new EditViewModel
            {
                Name = player.Name,
                Id = id
            };

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditViewModel form)
        {
            try
            {
                var query = new PlayerQuery();
                var service = new PlayerService();

                var player = query.Get(form.Id);

                player.Name = form.Name;

                service.Save(player);
                return RedirectToAction("Profile", new { form.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public JsonResult RatingsOverTime(int id)
        {
            using (var adapter = new DataAccessAdapter())
            {
                var ratings = new EntityCollection<PostGameRatingDetailEntity>();
                var filter = new RelationPredicateBucket(PostGameRatingDetailFields.LeagueId == id);
                adapter.FetchEntityCollection(ratings, filter);

                var players = ratings.GroupBy(m => m.PlayerId);

                var result = new List<RatingResult>();

                foreach (var player in players)
                {
                    var toAdd = new RatingResult
                    {
                        PlayerName = player.First().PlayerName,
                        TimeRating = player
                            .OrderByDescending(m => m.TimeStamp)
                            .Take(100)
                            .OrderBy(m => m.TimeStamp)
                            .Select(m => new Tuple<string, short>(m.TimeStamp.ToString("M/d/y h:m:s"), m.Rating))
                            .ToArray()
                    };
                    result.Add(toAdd);
                }

                var toRet = result.Select(m => new
                {
                    name = m.PlayerName,
                    data = m.TimeRating.Select(n => new
                    {
                        x = n.Item1,
                        y = n.Item2
                    })
                });

                return Json(toRet.ToArray(), JsonRequestBehavior.AllowGet);
            }
        }

        [OutputCache(VaryByParam = "*", Duration = 0, NoStore = true)]
        public JsonResult Record(int id)
        {
            var games = new EntityCollection<GameEntity>();
            var filter = new RelationPredicateBucket(GameFields.WinnerId == id | GameFields.LoserId == id);

            using (var adapter = new DataAccessAdapter())
            {
                adapter.FetchEntityCollection(games, filter);
            }

            var toRet = games.OrderBy(m => m.TimeStamp).Select(m => new
            {
                val = m.WinnerId == id ? 1 : -1
            });

            return Json(toRet.Take(100).Select(m => m.val).ToArray(), JsonRequestBehavior.AllowGet);
        }

        public static double DateTimeToUnixTimestamp(DateTime dateTime)
        {
            return (dateTime - new DateTime(1970, 1, 1).ToLocalTime()).TotalSeconds;
        }

        private class RatingResult
        {
            public string PlayerName { get; set; }
            public IEnumerable<Tuple<string, short>> TimeRating { get; set; }
        }

        //public ActionResult Edit(int id)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Edit(EditViewModel form)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}

        //public ActionResult Delete(int id)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Delete(DeleteViewModel form)
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}
    }
}

source/RatingTracker.Web.Mvc/Views/Player/Create.cshtml
@model RatingTracker.Models.Player.CreateViewModel
@{
    ViewBag.Title = "Add New Player";
}
<div class="row">
    <div class="col-xs-12">
        <h1>Add Player</h1>
        @using (Html.BeginForm("Create", "Player", null, FormMethod.Post, new { role = "form" }))
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    @Html.ValidationSummary()
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label>Name</label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                    <input type="submit" class="btn btn-success" value="Submit" />
                </div>

            </div>
        }
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/Player/Edit.cshtml
@model RatingTracker.Models.Player.EditViewModel
@{
    ViewBag.Title = "Edit Player";
}
<div class="row">
    <div class="col-xs-12">
        <h1>Edit Player</h1>
        @using (Html.BeginForm("Edit", "Player", null, FormMethod.Post, new { role = "form" }))
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    @Html.ValidationSummary()
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label>Name</label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                    @Html.HiddenFor(m => m.Id)
                    <input type="submit" class="btn btn-success" value="Submit" />
                    @Html.ActionLink("Cancel", "Profile", new { Model.Id }, new { @class = "btn btn-default" })
                </div>

            </div>
        }
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/Player/Index.cshtml
@model RatingTracker.Models.Player.IndexViewModel
@{
    ViewBag.Title = "Players";
}

<h1>All Players</h1>

<div class="row">
    <div class="col-xs-12">
        <div class="list-group">
            @foreach (var player in Model.Players.OrderBy(m=>m.Name))
            {
                @Html.ActionLink(player.Name, "Profile", "Player", new { id = player.Id }, new { @class="list-group-item"})
            }
        </div>
        @Html.ActionLink("Add Player", "Create", null, new { @class = "btn btn-primary" })
    </div>
</div>

source/RatingTracker.Web.Mvc/Views/Player/League.cshtml
@model RatingTracker.Models.Player.LeagueViewModel
@{
    ViewBag.Title = "Player League Profile";
}



<div class="row">
    <div class="col-xs-12">
        <h1>
            @Model.Player.Name
            <span id="winloss"></span>

        </h1>
        <div class="row">
            <div class="col-md-6">
                <h2>Stats</h2>
                <table class="table table-condensed">
                    <tr><td>Current Rating:</td><td>@Model.LeaguePlayer.CurrentRating</td></tr>
                    <tr><td>Highest Rating:</td><td>@Model.MaxRating</td></tr>
                    <tr><td>Wins:</td><td>@Model.Games.Count(m => m.WinnerPlayerId == Model.Player.Id)</td></tr>
                    <tr><td>Losses:</td><td>@Model.Games.Count(m => m.LoserPlayerId == Model.Player.Id)</td></tr>
                    <tr><td>Games Played:</td><td>@Model.Games.Count()</td></tr>
                </table>
                @Html.ActionLink("League Roster", "Details", "League", new { id = Model.LeaguePlayer.LeagueId }, new { @class = "btn btn-xs btn-default" })
            </div>

            <div class="col-md-6">
                <h2>League Games</h2>
                <table class="table table-condensed">
                    <tr><th>Winner</th><th>Loser</th><th>Date</th></tr>
                    @foreach (var game in Model.Games.OrderByDescending(m => m.TimeStamp).Take(25))
                    {
                        if (game.IsCriticalUpset)
                        {
                            <tr class="danger">
                                <td class="text-success">@game.WinnerName (@(Math.Round(game.Bias * 100, 1))%)</td>
                                <td class="text-danger">@game.LoserName (@(Math.Round(100 - game.Bias * 100, 1))%)</td>
                                <td>@game.TimeStamp</td>
                            </tr>
                        }
                        else if (game.IsUpset)
                        {

                            <tr class="warning">
                                <td class="text-success">@game.WinnerName (@(Math.Round(game.Bias * 100, 1))%)</td>
                                <td class="text-danger">@game.LoserName (@(Math.Round(100 - game.Bias * 100, 1))%)</td>
                                <td>@game.TimeStamp</td>
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td class="text-success">@game.WinnerName (@(Math.Round(game.Bias * 100, 1))%)</td>
                                <td class="text-danger">@game.LoserName (@(Math.Round(100 - game.Bias * 100, 1))%)</td>
                                <td>@game.TimeStamp</td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>



</div>

@section scripts
{
    <script src="~/Scripts/jquery.sparkline.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $.get("/player/record/@Model.LeaguePlayer.Id", function (data) {
                $("#winloss").sparkline(data, {
                    type: 'tristate',
                    posBarColor: '#7be512',
                    negBarColor: '#bf0000',
                    disableTooltips: true
                });
            });
        });
    </script>
}

source/RatingTracker.Web.Mvc/Views/Player/Profile.cshtml
@model RatingTracker.Models.Player.ProfileViewModel
@{
    ViewBag.Title = "Player Profile";
}



<div class="row">
    <div class="col-xs-12">
        <h1>
            @Model.Player.Name
        </h1>
        <div class="row">
            <div class="col-sm-6">
                <h2>Quick Stats</h2>
                <table class="table table-condensed">
                    <tr><td>Wins:</td><td>@Model.Games.Count(m => m.WinnerPlayerId == Model.Player.Id)</td></tr>
                    <tr><td>Losses:</td><td>@Model.Games.Count(m => m.LoserPlayerId == Model.Player.Id)</td></tr>
                    <tr><td>Games Played:</td><td>@Model.Games.Count()</td></tr>
                </table>
               
                <a href="/player" class="btn btn-primary">Back</a>
                @Html.ActionLink("Edit", "Edit", new { Model.Player.Id }, new { @class = "btn btn-info" })


            </div>
            <div class="col-sm-6">
                <h2>Leagues</h2>
                <div class="list-group">
                    @foreach (var league in Model.Leagues)
                    {
                        @Html.ActionLink(league.LeagueName, "League", "Player", new { id = league.LeaguePlayerId }, new { @class = "list-group-item" })
                    }
                </div>
            </div>
        </div>
    </div>
</div>
